Repository rcardin/yaes, pull requests merged in 2025-05, with the labels that each got.

#36 Create an Effect to Implement Streaming
  README.md
  build.sbt
  yaes-core/src/main/scala/in/rcard/yaes/Async.scala
  yaes-core/src/test/scala/in/rcard/yaes/AsyncSpec.scala
  yaes-data/README.md
  yaes-data/src/main/scala/in/rcard/yaes/Flow.scala
  yaes-data/src/test/scala/in/rcard/yaes/FlowSpec.scala
Labels: enhancement

#39 Fixed a typo in fold
  yaes-data/src/main/scala/in/rcard/yaes/Flow.scala
Labels: enhancement, typo

#38 Add unfold and zipWithIndex methods
  yaes-data/src/main/scala/in/rcard/yaes/Flow.scala
  yaes-data/src/test/scala/in/rcard/yaes/FlowSpec.scala
Labels: enhancement

#40 Adds zipWith operation on flows
  build.sbt
  yaes-core/src/main/scala/in/rcard/yaes/Async.scala
  yaes-core/src/test/scala/in/rcard/yaes/FlowZipWithSpec.scala
Labels: enhancement, yaes-core
